using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Rend.Core.Values;
using Xunit;

namespace Rend.Pdf.Tests
{
    /// <summary>
    /// Tests for <see cref="PdfOverlay"/>, <see cref="PdfOverlays"/> (static),
    /// and <see cref="IPdfOverlay"/> argument validation.
    /// </summary>
    public class OverlayTests
    {
        private readonly IPdfOverlay _overlay = new PdfOverlay();

        /// <summary>Minimal valid PDF for testing, generated by our own PdfDocument.</summary>
        private static byte[] MinimalPdf()
        {
            using var doc = new PdfDocument(new PdfDocumentOptions { Compression = PdfCompression.None });
            doc.AddPage(612, 792);
            using var ms = new MemoryStream();
            doc.Save(ms);
            return ms.ToArray();
        }

        /// <summary>Creates a minimal valid 1x1 red PNG (67 bytes).</summary>
        private static byte[] CreateMinimalPng()
        {
            using var ms = new MemoryStream();
            // PNG signature
            ms.Write(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }, 0, 8);

            // IHDR chunk: 1x1, 8-bit RGB
            var ihdr = new byte[] {
                0x00, 0x00, 0x00, 0x0D,                         // length = 13
                0x49, 0x48, 0x44, 0x52,                         // "IHDR"
                0x00, 0x00, 0x00, 0x01,                         // width = 1
                0x00, 0x00, 0x00, 0x01,                         // height = 1
                0x08, 0x02,                                      // 8-bit RGB
                0x00, 0x00, 0x00,                                // compression, filter, interlace
                0x72, 0x73, 0xC4, 0x01                           // CRC (pre-computed)
            };
            ms.Write(ihdr, 0, ihdr.Length);

            // IDAT chunk: zlib-compressed scanline (filter=0, R=255, G=0, B=0)
            var idat = new byte[] {
                0x00, 0x00, 0x00, 0x0C,                         // length = 12
                0x49, 0x44, 0x41, 0x54,                         // "IDAT"
                0x08, 0xD7,                                      // zlib header
                0x63, 0xF8, 0xCF, 0xC0, 0x00, 0x00,             // deflate data
                0x01, 0x01, 0x01, 0x00,                          // zlib checksum
                0x18, 0xDD, 0x8D, 0xB4                           // CRC (pre-computed)
            };
            ms.Write(idat, 0, idat.Length);

            // IEND chunk
            var iend = new byte[] {
                0x00, 0x00, 0x00, 0x00,                         // length = 0
                0x49, 0x45, 0x4E, 0x44,                         // "IEND"
                0xAE, 0x42, 0x60, 0x82                           // CRC
            };
            ms.Write(iend, 0, iend.Length);

            return ms.ToArray();
        }

        // ── Argument validation ──

        [Fact]
        public async Task ApplyAsync_ByteArray_NullPdf_Throws()
        {
            await Assert.ThrowsAnyAsync<ArgumentException>(() =>
                _overlay.ApplyAsync(null!, new List<PdfOverlayElement>()));
        }

        [Fact]
        public async Task ApplyAsync_ByteArray_EmptyPdf_Throws()
        {
            await Assert.ThrowsAnyAsync<ArgumentException>(() =>
                _overlay.ApplyAsync(Array.Empty<byte>(), new List<PdfOverlayElement>()));
        }

        [Fact]
        public async Task ApplyAsync_ByteArray_NullElements_Throws()
        {
            await Assert.ThrowsAsync<ArgumentNullException>(() =>
                _overlay.ApplyAsync(MinimalPdf(), null!));
        }

        [Fact]
        public async Task ApplyAsync_Stream_NullInput_Throws()
        {
            await Assert.ThrowsAsync<ArgumentNullException>(() =>
                _overlay.ApplyAsync(null!, new MemoryStream(), new List<PdfOverlayElement>()));
        }

        [Fact]
        public async Task ApplyAsync_Stream_NullOutput_Throws()
        {
            using var input = new MemoryStream(MinimalPdf());
            await Assert.ThrowsAsync<ArgumentNullException>(() =>
                _overlay.ApplyAsync(input, null!, new List<PdfOverlayElement>()));
        }

        [Fact]
        public async Task ApplyAsync_Stream_NullElements_Throws()
        {
            using var input = new MemoryStream(MinimalPdf());
            using var output = new MemoryStream();
            await Assert.ThrowsAsync<ArgumentNullException>(() =>
                _overlay.ApplyAsync(input, output, null!));
        }

        // ── Functional tests ──

        [Fact]
        public async Task ApplyAsync_EmptyElements_ReturnsPdf()
        {
            var pdf = MinimalPdf();
            var result = await _overlay.ApplyAsync(pdf, new List<PdfOverlayElement>());

            Assert.NotNull(result);
            Assert.True(result.Length > 0);
            Assert.Equal((byte)'%', result[0]);
        }

        [Fact]
        public async Task ApplyAsync_TextOverlay_ReturnsPdf()
        {
            var pdf = MinimalPdf();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay
                {
                    Page = 1,
                    X = 100,
                    Y = 100,
                    Text = "Hello World",
                    FontSize = 14,
                    FontFamily = "Helvetica"
                }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);

            Assert.NotNull(result);
            Assert.True(result.Length > pdf.Length, "Overlaid PDF should be larger");
        }

        [Fact]
        public async Task ApplyAsync_StreamOverload_WritesOutput()
        {
            using var input = new MemoryStream(MinimalPdf());
            using var output = new MemoryStream();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay { Page = 1, X = 50, Y = 50, Text = "Stream test" }
            };

            await _overlay.ApplyAsync(input, output, elements);

            Assert.True(output.Length > 0);
        }

        [Fact]
        public async Task ApplyAsync_TextOverlay_BoldItalic()
        {
            var pdf = MinimalPdf();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay
                {
                    Page = 1, X = 10, Y = 10,
                    Text = "Bold Italic",
                    Bold = true, Italic = true,
                    FontFamily = "Helvetica"
                }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);
            Assert.NotNull(result);
            Assert.True(result.Length > 0);
        }

        [Fact]
        public async Task ApplyAsync_TextOverlay_CourierFont()
        {
            var pdf = MinimalPdf();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay
                {
                    Page = 1, X = 10, Y = 10,
                    Text = "Courier text",
                    FontFamily = "Courier"
                }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);
            Assert.NotNull(result);
        }

        [Fact]
        public async Task ApplyAsync_TextOverlay_TimesFont()
        {
            var pdf = MinimalPdf();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay
                {
                    Page = 1, X = 10, Y = 10,
                    Text = "Times text",
                    FontFamily = "Times"
                }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);
            Assert.NotNull(result);
        }

        [Fact]
        public async Task ApplyAsync_TextOverlay_WithColor()
        {
            var pdf = MinimalPdf();
            var elements = new List<PdfOverlayElement>
            {
                new TextOverlay
                {
                    Page = 1, X = 10, Y = 10,
                    Text = "Red text",
                    Color = CssColor.FromRgba(255, 0, 0)
                }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);
            Assert.NotNull(result);
        }

        [Fact]
        public async Task ApplyAsync_ImageOverlay_ReturnsPdf()
        {
            var pdf = MinimalPdf();
            byte[] png = CreateMinimalPng();
            var elements = new List<PdfOverlayElement>
            {
                new ImageOverlay { Page = 1, X = 100, Y = 100, Width = 50, Height = 50, Data = png }
            };

            var result = await _overlay.ApplyAsync(pdf, elements);

            Assert.NotNull(result);
            Assert.True(result.Length > pdf.Length, "PDF with image overlay should be larger than original");
        }

        // ── Static facade (PdfOverlays) ──

        [Fact]
        public async Task PdfOverlays_ApplyAsync_ByteArray_Works()
        {
            var pdf = MinimalPdf();
            var result = await PdfOverlays.ApplyAsync(pdf, new List<PdfOverlayElement>());

            Assert.NotNull(result);
            Assert.True(result.Length > 0);
        }

        [Fact]
        public async Task PdfOverlays_ApplyAsync_Stream_Works()
        {
            using var input = new MemoryStream(MinimalPdf());
            using var output = new MemoryStream();

            await PdfOverlays.ApplyAsync(input, output, new List<PdfOverlayElement>());

            Assert.True(output.Length > 0);
        }

        // ── Model tests ──

        [Fact]
        public void TextOverlay_DefaultValues()
        {
            var overlay = new TextOverlay();
            Assert.Equal(1, overlay.Page);
            Assert.Equal(0f, overlay.X);
            Assert.Equal(0f, overlay.Y);
            Assert.Equal("", overlay.Text);
            Assert.Equal(12f, overlay.FontSize);
            Assert.Equal("Helvetica", overlay.FontFamily);
            Assert.False(overlay.Bold);
            Assert.False(overlay.Italic);
        }

        [Fact]
        public void ImageOverlay_DefaultValues()
        {
            var overlay = new ImageOverlay();
            Assert.Equal(1, overlay.Page);
            Assert.Equal(0f, overlay.X);
            Assert.Equal(0f, overlay.Y);
            Assert.Empty(overlay.Data);
            Assert.Equal(0f, overlay.Width);
            Assert.Equal(0f, overlay.Height);
        }
    }
}
