using Xunit;
using Xunit.Abstractions;

namespace Rend.Tests.Layout
{
    public class WptBlockBoxSizingComparisonTests
    {
        private readonly ITestOutputHelper _output;
        public WptBlockBoxSizingComparisonTests(ITestOutputHelper output) { _output = output; }

        [Fact] public void ContentBox_Width200_Padding20_Content200() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='width:200px;padding:20px;height:30px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); }
        [Fact] public void BorderBox_Width200_Padding20_Content160() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:200px;padding:20px;height:80px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 160) < 2); }
        [Fact] public void ContentBox_Width200_Border10_Content200() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='width:200px;border:10px solid;height:30px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); }
        [Fact] public void BorderBox_Width200_Border10_Content180() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:200px;border:10px solid;height:60px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 180) < 2); }
        [Fact] public void ContentBox_Width200_Both_Content200() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='width:200px;padding:15px;border:5px solid;height:30px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); }
        [Fact] public void BorderBox_Width200_Both_Content160() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:200px;padding:15px;border:5px solid;height:80px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 160) < 2); }
        [Fact] public void ContentBox_Height100_Padding10_Content100() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='width:100px;height:100px;padding:10px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 100) < 2); }
        [Fact] public void BorderBox_Height100_Padding10_Content80() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:100px;height:100px;padding:10px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 80) < 2); }
        [Fact] public void ContentBox_NoPaddingNoBorder_Same() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='width:200px;height:100px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 100) < 2); }
        [Fact] public void BorderBox_NoPaddingNoBorder_Same() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:200px;height:100px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 100) < 2); }
        [Fact] public void BorderBox_LargePadding_Content0() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:80px;padding:40px;height:80px'></div></body>"); Assert.True(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width < 2); Assert.True(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height < 2); }
        [Fact] public void BorderBox_AsymmetricPadding() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='t' style='box-sizing:border-box;width:200px;padding:10px 20px 30px 40px;height:100px'></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 140) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 60) < 2); }
        [Fact] public void ContentBox_50Pct_Padding20_ChildWidth() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='width:400px'><div id='t' style='width:50%;padding:20px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 200) < 2); }
        [Fact] public void BorderBox_50Pct_Padding20_ChildWidth() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='width:400px'><div id='t' style='box-sizing:border-box;width:50%;padding:20px;height:80px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 160) < 2); }
        [Fact] public void BorderBox_InFlex() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='box-sizing:border-box;flex:0 0 150px;padding:20px;border:5px solid;height:60px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width + 40 + 10 - 150) < 2); }
        [Fact] public void BorderBox_InGrid() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:200px;width:200px'><div id='t' style='box-sizing:border-box;width:200px;padding:20px;border:10px solid;height:80px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width + 40 + 20 - 200) < 2); }
    }
}
