using Xunit;
using Xunit.Abstractions;

namespace Rend.Tests.Layout
{
    public class WptFlexboxRatioGrowTests
    {
        private readonly ITestOutputHelper _output;
        public WptFlexboxRatioGrowTests(ITestOutputHelper output) { _output = output; }

        [Fact] public void R1_2_In300_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 200) < 2); }
        [Fact] public void R1_2_In300_X() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.X - 100) < 2); }
        [Fact] public void R1_3_In400_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:3 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 300) < 2); }
        [Fact] public void R2_3_In500_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:500px'><div id='a' style='flex:2 0 0px;height:30px'></div><div id='b' style='flex:3 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 200) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 300) < 2); }
        [Fact] public void R1_1_2_In400_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:1 0 0px;height:30px'></div><div id='c' style='flex:2 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.Width - 200) < 2); }
        [Fact] public void R1_2_3_In600_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:600px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div><div id='c' style='flex:3 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 200) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.Width - 300) < 2); }
        [Fact] public void R1_2_3_In600_X() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:600px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div><div id='c' style='flex:3 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.X - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.X - 300) < 2); }
        [Fact] public void R3_1_In400_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='flex:3 0 0px;height:30px'></div><div id='b' style='flex:1 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 300) < 2); }
        [Fact] public void R1_4_In500_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:500px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:4 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 400) < 2); }
        [Fact] public void Col_R1_2_In300_H() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-direction:column;width:200px;height:300px'><div id='a' style='flex:1'></div><div id='b' style='flex:2'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Height - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Height - 200) < 2); }
        [Fact] public void Col_R1_2_3_In600_H() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-direction:column;width:200px;height:600px'><div id='a' style='flex:1'></div><div id='b' style='flex:2'></div><div id='c' style='flex:3'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Height - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.Height - 300) < 2); }
        [Fact] public void R1_2_Gap20_In320_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;gap:20px;width:320px'><div id='a' style='flex:1 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 200) < 2); }
        [Fact] public void R1_2_Basis_50_100() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='a' style='flex:1 0 50px;height:30px'></div><div id='b' style='flex:1 0 100px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 125) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.Width - 175) < 2); }
        [Fact] public void R2_2_In400_W() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='flex:2 0 0px;height:30px'></div><div id='b' style='flex:2 0 0px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 200) < 2); }
    }
}
