using Xunit;
using Xunit.Abstractions;

namespace Rend.Tests.Layout
{
    public class WptFlexboxItemBorderTests
    {
        private readonly ITestOutputHelper _output;
        public WptFlexboxItemBorderTests(ITestOutputHelper output) { _output = output; }

        [Fact] public void Border_ReducesContent() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='flex:0 0 100px;border:5px solid;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.BorderLeftWidth - 5) < 1); }
        [Fact] public void Border_IndividualSides() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='flex:0 0 100px;border-left:3px solid;border-right:7px solid;border-top:2px solid;border-bottom:4px solid;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.BorderLeftWidth - 3) < 1); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.BorderRightWidth - 7) < 1); }
        [Fact] public void Border_OffsetsSibling() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div style='flex:0 0 100px;border:5px solid;height:30px'></div><div id='b' style='width:50px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.X - 110) < 2); }
        [Fact] public void Border_WithPadding() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='flex:0 0 100px;padding:10px;border:5px solid;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 100) < 2); }
        [Fact] public void Border_WithBorderBox() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='box-sizing:border-box;flex:0 0 150px;padding:15px;border:5px solid;height:60px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width + 30 + 10 - 150) < 2); }
        [Fact] public void Border_WithGrow() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='a' style='flex:1;border:5px solid;height:30px'></div><div id='b' style='flex:1;border:5px solid;height:30px'></div></div></body>"); float totalA = LayoutTestHelper.FindById(r,"a")!.ContentRect.Width + 10; float totalB = LayoutTestHelper.FindById(r,"b")!.ContentRect.Width + 10; Assert.True(System.Math.Abs(totalA + totalB - 300) < 3); }
        [Fact] public void Border_WithShrink() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:150px'><div id='a' style='flex:0 1 100px;border:5px solid;min-width:0;height:30px'></div><div id='b' style='flex:0 1 100px;border:5px solid;min-width:0;height:30px'></div></div></body>"); float totalA = LayoutTestHelper.FindById(r,"a")!.ContentRect.Width + 10; float totalB = LayoutTestHelper.FindById(r,"b")!.ContentRect.Width + 10; Assert.True(System.Math.Abs(totalA + totalB - 150) < 3); }
        [Fact] public void Border_StyleNone_ZeroWidth() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='flex:0 0 100px;border:5px none;height:30px'></div></div></body>"); Assert.True(LayoutTestHelper.FindById(r,"t")!.BorderLeftWidth < 1); }
        [Fact] public void Border_OnStretchItem() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;height:100px;width:300px'><div id='t' style='width:100px;border:10px solid'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height + 20 - 100) < 2); }
        [Fact] public void Border_Column() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-direction:column;width:200px;height:200px'><div id='t' style='flex:0 0 80px;border:10px solid'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Height - 80) < 2); }
        [Fact] public void Border_TwoItems_Positions() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='a' style='width:80px;border:5px solid;height:30px'></div><div id='b' style='width:80px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.X - 90) < 2); }
        [Fact] public void Border_WithMargin() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='width:80px;border:5px solid;margin:10px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.X - 15) < 2); }
        [Fact] public void Border_LargeWidth() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:300px'><div id='t' style='flex:0 0 100px;border:20px solid;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.BorderLeftWidth - 20) < 1); }
        [Fact] public void Border_WithGap() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;gap:10px;width:300px'><div id='a' style='width:80px;border:5px solid;height:30px'></div><div id='b' style='width:80px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"b")!.ContentRect.X - 100) < 2); }
    }
}
