using Xunit;
using Xunit.Abstractions;

namespace Rend.Tests.Layout
{
    public class WptFlexboxSixItemTests
    {
        private readonly ITestOutputHelper _output;
        public WptFlexboxSixItemTests(ITestOutputHelper output) { _output = output; }

        [Fact] public void SixEqual_Grow1_Width600() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:600px'><div id='a' style='flex:1;height:30px'></div><div style='flex:1;height:30px'></div><div style='flex:1;height:30px'></div><div style='flex:1;height:30px'></div><div style='flex:1;height:30px'></div><div id='f' style='flex:1;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 100) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.Width - 100) < 2); }
        [Fact] public void SixFixed_40px_Positions() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='width:40px;height:30px'></div><div style='width:40px;height:30px'></div><div style='width:40px;height:30px'></div><div style='width:40px;height:30px'></div><div style='width:40px;height:30px'></div><div id='f' style='width:40px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 200) < 2); }
        [Fact] public void SixItems_Gap10() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;gap:10px;width:400px'><div id='a' style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div id='f' style='width:30px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 200) < 2); }
        [Fact] public void SixItems_SpaceBetween() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;justify-content:space-between;width:400px'><div id='a' style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div id='f' style='width:30px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.X - 0) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 370) < 2); }
        [Fact] public void SixItems_Center() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;justify-content:center;width:400px'><div id='a' style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.X - 110) < 2); }
        [Fact] public void SixItems_Column() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-direction:column;width:200px'><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.Y - 100) < 2); }
        [Fact] public void SixItems_ColumnGrow() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-direction:column;width:200px;height:300px'><div id='a' style='flex:1'></div><div style='flex:1'></div><div style='flex:1'></div><div style='flex:1'></div><div style='flex:1'></div><div id='f' style='flex:1'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Height - 50) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.Y - 250) < 2); }
        [Fact] public void SixItems_FlexEnd() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;justify-content:flex-end;width:400px'><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div style='width:30px;height:30px'></div><div id='f' style='width:30px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 370) < 2); }
        [Fact] public void SixItems_Order() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;width:400px'><div id='a' style='order:6;width:30px;height:30px'></div><div style='order:4;width:30px;height:30px'></div><div id='c' style='order:1;width:30px;height:30px'></div><div style='order:5;width:30px;height:30px'></div><div style='order:3;width:30px;height:30px'></div><div style='order:2;width:30px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.X - 0) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.X - 150) < 2); }
        [Fact] public void SixItems_Wrap_3PerLine() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:flex;flex-wrap:wrap;width:200px'><div id='a' style='width:60px;height:30px'></div><div style='width:60px;height:30px'></div><div style='width:60px;height:30px'></div><div id='d' style='width:60px;height:30px'></div><div style='width:60px;height:30px'></div><div id='f' style='width:60px;height:30px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Y - 0) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"d")!.ContentRect.Y - 30) < 2); }
    }
}
