using Xunit;
using Xunit.Abstractions;

namespace Rend.Tests.Layout
{
    public class WptGridSixColumnTests
    {
        private readonly ITestOutputHelper _output;
        public WptGridSixColumnTests(ITestOutputHelper output) { _output = output; }

        [Fact] public void SixCol_Equal_1fr() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,1fr);width:300px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 50) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.Width - 50) < 2); }
        [Fact] public void SixCol_Positions() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,50px);width:300px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.X - 0) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 250) < 2); }
        [Fact] public void SixCol_WithGap() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,40px);column-gap:8px;width:280px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.X - 240) < 2); }
        [Fact] public void SixCol_SpanAll() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,50px);width:300px'><div id='t' style='grid-column:1/-1;height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 300) < 2); }
        [Fact] public void SixCol_Span3() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,50px);width:300px'><div id='t' style='grid-column:span 3;height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"t")!.ContentRect.Width - 150) < 2); }
        [Fact] public void SixCol_TwelveItems_TwoRows() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,50px);grid-auto-rows:30px;width:300px'><div></div><div></div><div></div><div></div><div></div><div></div><div id='g'></div><div></div><div></div><div></div><div></div><div id='l'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"g")!.ContentRect.Y - 30) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"l")!.ContentRect.X - 250) < 2); }
        [Fact] public void SixCol_MixedWidths() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:30px 40px 50px 60px 70px 50px;width:300px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 30) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"f")!.ContentRect.Width - 50) < 2); }
        [Fact] public void SixCol_Percent() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:repeat(6,16.66%);width:300px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 50) < 2); }
        [Fact] public void SixCol_Fr_1_1_2_1_1_2() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div style='display:grid;grid-template-columns:1fr 1fr 2fr 1fr 1fr 2fr;width:400px'><div id='a' style='height:20px'></div><div style='height:20px'></div><div id='c' style='height:20px'></div><div style='height:20px'></div><div style='height:20px'></div><div id='f' style='height:20px'></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"a")!.ContentRect.Width - 50) < 2); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"c")!.ContentRect.Width - 100) < 2); }
        [Fact] public void SixCol_ContainerHeight() { var r = LayoutTestHelper.Layout(@"<body style='margin:0'><div id='g' style='display:grid;grid-template-columns:repeat(6,50px);grid-template-rows:40px;width:300px'><div></div><div></div><div></div><div></div><div></div><div></div></div></body>"); Assert.True(System.Math.Abs(LayoutTestHelper.FindById(r,"g")!.ContentRect.Height - 40) < 2); }
    }
}
