// Licensed to the .NET Foundation under one or more agreements.
// This file contains the most common ~250 named HTML character references.

using System;

namespace Rend.Html.Parser.Internal
{
    /// <summary>
    /// Lookup table for named HTML character references.
    /// Uses parallel sorted arrays with binary search for fast O(log n) lookup.
    /// </summary>
    internal static class CharRefTable
    {
        // ---------------------------------------------------------------
        //  Parallel sorted arrays – Names[i] maps to CodePoints[i].
        //  MUST be kept in ordinal (case-sensitive) sorted order.
        // ---------------------------------------------------------------

        private static readonly string[] Names =
        {
            "AElig",      // 0
            "Aacute",     // 1
            "Acirc",      // 2
            "Agrave",     // 3
            "Alpha",      // 4
            "Aring",      // 5
            "Atilde",     // 6
            "Auml",       // 7
            "Beta",       // 8
            "Ccedil",     // 9
            "Chi",        // 10
            "Dagger",     // 11
            "Delta",      // 12
            "ETH",        // 13
            "Eacute",     // 14
            "Ecirc",      // 15
            "Egrave",     // 16
            "Epsilon",    // 17
            "Eta",        // 18
            "Euml",       // 19
            "Gamma",      // 20
            "Iacute",     // 21
            "Icirc",      // 22
            "Igrave",     // 23
            "Iota",       // 24
            "Iuml",       // 25
            "Kappa",      // 26
            "Lambda",     // 27
            "Mu",         // 28
            "Ntilde",     // 29
            "Nu",         // 30
            "OElig",      // 31
            "Oacute",     // 32
            "Ocirc",      // 33
            "Ograve",     // 34
            "Omega",      // 35
            "Omicron",    // 36
            "Oslash",     // 37
            "Otilde",     // 38
            "Ouml",       // 39
            "Phi",        // 40
            "Pi",         // 41
            "Prime",      // 42
            "Psi",        // 43
            "Rho",        // 44
            "Scaron",     // 45
            "Sigma",      // 46
            "THORN",      // 47
            "Tau",        // 48
            "Theta",      // 49
            "Uacute",     // 50
            "Ucirc",      // 51
            "Ugrave",     // 52
            "Upsilon",    // 53
            "Uuml",       // 54
            "Xi",         // 55
            "Yacute",     // 56
            "Yuml",       // 57
            "Zeta",       // 58
            "aacute",     // 59
            "acirc",      // 60
            "acute",      // 61
            "aelig",      // 62
            "agrave",     // 63
            "alefsym",    // 64
            "alpha",      // 65
            "amp",        // 66
            "and",        // 67
            "ang",        // 68
            "apos",       // 69
            "aring",      // 70
            "asymp",      // 71
            "atilde",     // 72
            "auml",       // 73
            "bdquo",      // 74
            "beta",       // 75
            "brvbar",     // 76
            "bull",       // 77
            "cap",        // 78
            "ccedil",     // 79
            "cedil",      // 80
            "cent",       // 81
            "chi",        // 82
            "circ",       // 83
            "clubs",      // 84
            "cong",       // 85
            "copy",       // 86
            "crarr",      // 87
            "cup",        // 88
            "curren",     // 89
            "dArr",       // 90
            "dagger",     // 91
            "darr",       // 92
            "deg",        // 93
            "delta",      // 94
            "diams",      // 95
            "divide",     // 96
            "eacute",     // 97
            "ecirc",      // 98
            "egrave",     // 99
            "empty",      // 100
            "emsp",       // 101
            "ensp",       // 102
            "epsilon",    // 103
            "equiv",      // 104
            "eta",        // 105
            "eth",        // 106
            "euml",       // 107
            "euro",       // 108
            "exist",      // 109
            "fnof",       // 110
            "forall",     // 111
            "frac12",     // 112
            "frac14",     // 113
            "frac34",     // 114
            "frasl",      // 115
            "gamma",      // 116
            "ge",         // 117
            "gt",         // 118
            "hArr",       // 119
            "harr",       // 120
            "hearts",     // 121
            "hellip",     // 122
            "iacute",     // 123
            "icirc",      // 124
            "iexcl",      // 125
            "igrave",     // 126
            "image",      // 127
            "infin",      // 128
            "int",        // 129
            "iota",       // 130
            "iquest",     // 131
            "isin",       // 132
            "iuml",       // 133
            "kappa",      // 134
            "lArr",       // 135
            "lambda",     // 136
            "lang",       // 137
            "laquo",      // 138
            "larr",       // 139
            "lceil",      // 140
            "ldquo",      // 141
            "le",         // 142
            "lfloor",     // 143
            "lowast",     // 144
            "loz",        // 145
            "lrm",        // 146
            "lsaquo",     // 147
            "lsquo",      // 148
            "lt",         // 149
            "macr",       // 150
            "mdash",      // 151
            "micro",      // 152
            "middot",     // 153
            "minus",      // 154
            "mu",         // 155
            "nabla",      // 156
            "nbsp",       // 157
            "ndash",      // 158
            "ne",         // 159
            "ni",         // 160
            "not",        // 161
            "notin",      // 162
            "nsub",       // 163
            "ntilde",     // 164
            "nu",         // 165
            "oacute",     // 166
            "ocirc",      // 167
            "oelig",      // 168
            "ograve",     // 169
            "oline",      // 170
            "omega",      // 171
            "omicron",    // 172
            "oplus",      // 173
            "or",         // 174
            "ordf",       // 175
            "ordm",       // 176
            "oslash",     // 177
            "otilde",     // 178
            "otimes",     // 179
            "ouml",       // 180
            "para",       // 181
            "part",       // 182
            "permil",     // 183
            "phi",        // 184
            "pi",         // 185
            "piv",        // 186
            "plusmn",     // 187
            "pound",      // 188
            "prime",      // 189
            "prod",       // 190
            "prop",       // 191
            "psi",        // 192
            "quot",       // 193
            "rArr",       // 194
            "radic",      // 195
            "rang",       // 196
            "raquo",      // 197
            "rarr",       // 198
            "rceil",      // 199
            "rdquo",      // 200
            "real",       // 201
            "reg",        // 202
            "rfloor",     // 203
            "rho",        // 204
            "rlm",        // 205
            "rsaquo",     // 206
            "rsquo",      // 207
            "sbquo",      // 208
            "scaron",     // 209
            "sdot",       // 210
            "sect",       // 211
            "shy",        // 212
            "sigma",      // 213
            "sigmaf",     // 214
            "sim",        // 215
            "spades",     // 216
            "sub",        // 217
            "sube",       // 218
            "sum",        // 219
            "sup",        // 220
            "sup1",       // 221
            "sup2",       // 222
            "sup3",       // 223
            "supe",       // 224
            "szlig",      // 225
            "tau",        // 226
            "there4",     // 227
            "theta",      // 228
            "thetasym",   // 229
            "thinsp",     // 230
            "thorn",      // 231
            "tilde",      // 232
            "times",      // 233
            "trade",      // 234
            "uArr",       // 235
            "uacute",     // 236
            "uarr",       // 237
            "ucirc",      // 238
            "ugrave",     // 239
            "uml",        // 240
            "upsih",      // 241
            "upsilon",    // 242
            "uuml",       // 243
            "weierp",     // 244
            "xi",         // 245
            "yacute",     // 246
            "yen",        // 247
            "yuml",       // 248
            "zeta",       // 249
            "zwj",        // 250
            "zwnj",       // 251
        };

        private static readonly int[] CodePoints =
        {
            0x00C6, // AElig
            0x00C1, // Aacute
            0x00C2, // Acirc
            0x00C0, // Agrave
            0x0391, // Alpha
            0x00C5, // Aring
            0x00C3, // Atilde
            0x00C4, // Auml
            0x0392, // Beta
            0x00C7, // Ccedil
            0x03A7, // Chi
            0x2021, // Dagger
            0x0394, // Delta
            0x00D0, // ETH
            0x00C9, // Eacute
            0x00CA, // Ecirc
            0x00C8, // Egrave
            0x0395, // Epsilon
            0x0397, // Eta
            0x00CB, // Euml
            0x0393, // Gamma
            0x00CD, // Iacute
            0x00CE, // Icirc
            0x00CC, // Igrave
            0x0399, // Iota
            0x00CF, // Iuml
            0x039A, // Kappa
            0x039B, // Lambda
            0x039C, // Mu
            0x00D1, // Ntilde
            0x039D, // Nu
            0x0152, // OElig
            0x00D3, // Oacute
            0x00D4, // Ocirc
            0x00D2, // Ograve
            0x03A9, // Omega
            0x039F, // Omicron
            0x00D8, // Oslash
            0x00D5, // Otilde
            0x00D6, // Ouml
            0x03A6, // Phi
            0x03A0, // Pi
            0x2033, // Prime
            0x03A8, // Psi
            0x03A1, // Rho
            0x0160, // Scaron
            0x03A3, // Sigma
            0x00DE, // THORN
            0x03A4, // Tau
            0x0398, // Theta
            0x00DA, // Uacute
            0x00DB, // Ucirc
            0x00D9, // Ugrave
            0x03A5, // Upsilon
            0x00DC, // Uuml
            0x039E, // Xi
            0x00DD, // Yacute
            0x0178, // Yuml
            0x0396, // Zeta
            0x00E1, // aacute
            0x00E2, // acirc
            0x00B4, // acute
            0x00E6, // aelig
            0x00E0, // agrave
            0x2135, // alefsym
            0x03B1, // alpha
            0x0026, // amp
            0x2227, // and
            0x2220, // ang
            0x0027, // apos
            0x00E5, // aring
            0x2248, // asymp
            0x00E3, // atilde
            0x00E4, // auml
            0x201E, // bdquo
            0x03B2, // beta
            0x00A6, // brvbar
            0x2022, // bull
            0x2229, // cap
            0x00E7, // ccedil
            0x00B8, // cedil
            0x00A2, // cent
            0x03C7, // chi
            0x02C6, // circ
            0x2663, // clubs
            0x2245, // cong
            0x00A9, // copy
            0x21B5, // crarr
            0x222A, // cup
            0x00A4, // curren
            0x21D3, // dArr
            0x2020, // dagger
            0x2193, // darr
            0x00B0, // deg
            0x03B4, // delta
            0x2666, // diams
            0x00F7, // divide
            0x00E9, // eacute
            0x00EA, // ecirc
            0x00E8, // egrave
            0x2205, // empty
            0x2003, // emsp
            0x2002, // ensp
            0x03B5, // epsilon
            0x2261, // equiv
            0x03B7, // eta
            0x00F0, // eth
            0x00EB, // euml
            0x20AC, // euro
            0x2203, // exist
            0x0192, // fnof
            0x2200, // forall
            0x00BD, // frac12
            0x00BC, // frac14
            0x00BE, // frac34
            0x2044, // frasl
            0x03B3, // gamma
            0x2265, // ge
            0x003E, // gt
            0x21D4, // hArr
            0x2194, // harr
            0x2665, // hearts
            0x2026, // hellip
            0x00ED, // iacute
            0x00EE, // icirc
            0x00A1, // iexcl
            0x00EC, // igrave
            0x2111, // image
            0x221E, // infin
            0x222B, // int
            0x03B9, // iota
            0x00BF, // iquest
            0x2208, // isin
            0x00EF, // iuml
            0x03BA, // kappa
            0x21D0, // lArr
            0x03BB, // lambda
            0x27E8, // lang
            0x00AB, // laquo
            0x2190, // larr
            0x2308, // lceil
            0x201C, // ldquo
            0x2264, // le
            0x230A, // lfloor
            0x2217, // lowast
            0x25CA, // loz
            0x200E, // lrm
            0x2039, // lsaquo
            0x2018, // lsquo
            0x003C, // lt
            0x00AF, // macr
            0x2014, // mdash
            0x00B5, // micro
            0x00B7, // middot
            0x2212, // minus
            0x03BC, // mu
            0x2207, // nabla
            0x00A0, // nbsp
            0x2013, // ndash
            0x2260, // ne
            0x220B, // ni
            0x00AC, // not
            0x2209, // notin
            0x2284, // nsub
            0x00F1, // ntilde
            0x03BD, // nu
            0x00F3, // oacute
            0x00F4, // ocirc
            0x0153, // oelig
            0x00F2, // ograve
            0x203E, // oline
            0x03C9, // omega
            0x03BF, // omicron
            0x2295, // oplus
            0x2228, // or
            0x00AA, // ordf
            0x00BA, // ordm
            0x00F8, // oslash
            0x00F5, // otilde
            0x2297, // otimes
            0x00F6, // ouml
            0x00B6, // para
            0x2202, // part
            0x2030, // permil
            0x03C6, // phi
            0x03C0, // pi
            0x03D6, // piv
            0x00B1, // plusmn
            0x00A3, // pound
            0x2032, // prime
            0x220F, // prod
            0x221D, // prop
            0x03C8, // psi
            0x0022, // quot
            0x21D2, // rArr
            0x221A, // radic
            0x27E9, // rang
            0x00BB, // raquo
            0x2192, // rarr
            0x2309, // rceil
            0x201D, // rdquo
            0x211C, // real
            0x00AE, // reg
            0x230B, // rfloor
            0x03C1, // rho
            0x200F, // rlm
            0x203A, // rsaquo
            0x2019, // rsquo
            0x201A, // sbquo
            0x0161, // scaron
            0x22C5, // sdot
            0x00A7, // sect
            0x00AD, // shy
            0x03C3, // sigma
            0x03C2, // sigmaf
            0x223C, // sim
            0x2660, // spades
            0x2282, // sub
            0x2286, // sube
            0x2211, // sum
            0x2283, // sup
            0x00B9, // sup1
            0x00B2, // sup2
            0x00B3, // sup3
            0x2287, // supe
            0x00DF, // szlig
            0x03C4, // tau
            0x2234, // there4
            0x03B8, // theta
            0x03D1, // thetasym
            0x2009, // thinsp
            0x00FE, // thorn
            0x02DC, // tilde
            0x00D7, // times
            0x2122, // trade
            0x21D1, // uArr
            0x00FA, // uacute
            0x2191, // uarr
            0x00FB, // ucirc
            0x00F9, // ugrave
            0x00A8, // uml
            0x03D2, // upsih
            0x03C5, // upsilon
            0x00FC, // uuml
            0x2118, // weierp
            0x03BE, // xi
            0x00FD, // yacute
            0x00A5, // yen
            0x00FF, // yuml
            0x03B6, // zeta
            0x200D, // zwj
            0x200C, // zwnj
        };

        /// <summary>
        /// Attempts to resolve a named character reference to its Unicode code point.
        /// </summary>
        /// <param name="name">
        /// The entity name without the leading <c>&amp;</c> and trailing <c>;</c>.
        /// For example, pass <c>"amp"</c> rather than <c>"&amp;amp;"</c>.
        /// </param>
        /// <param name="codePoint">
        /// When this method returns <see langword="true"/>, contains the Unicode code point
        /// for the named reference; otherwise, <c>0</c>.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if the name was found; otherwise, <see langword="false"/>.
        /// </returns>
        public static bool TryLookup(string name, out int codePoint)
        {
            int index = Array.BinarySearch(Names, name, StringComparer.Ordinal);
            if (index >= 0)
            {
                codePoint = CodePoints[index];
                return true;
            }

            codePoint = 0;
            return false;
        }
    }
}
