using System;
using System.IO;
using Rend;
using Rend.Core.Values;

// Simple HTML to PDF
using (var output = File.Create("hello.pdf"))
{
    Render.ToPdf("<h1>Hello, World!</h1><p>Generated by Rend.</p>", output);
}

Console.WriteLine("Created hello.pdf");

// With options
var html = @"
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; color: #333; }
        h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        .total { font-weight: bold; text-align: right; }
    </style>
</head>
<body>
    <h1>Invoice #1234</h1>
    <p>Date: 2024-01-15</p>
    <table>
        <tr><th>Item</th><th>Qty</th><th>Price</th></tr>
        <tr><td>Widget A</td><td>10</td><td>$50.00</td></tr>
        <tr><td>Widget B</td><td>5</td><td>$75.00</td></tr>
        <tr><td>Service Fee</td><td>1</td><td>$150.00</td></tr>
    </table>
    <p class='total'>Total: $1,025.00</p>
</body>
</html>";

var options = new RenderOptions
{
    PageSize = PageSize.Letter,
    MarginTop = 48f,
    MarginRight = 48f,
    MarginBottom = 48f,
    MarginLeft = 48f,
    Title = "Invoice #1234",
    Author = "Acme Corp",
    HeaderHtml = "<div style='font-size:9px;color:#999;text-align:right;padding-right:10px'>Acme Corp</div>",
    FooterHtml = "<div style='font-size:9px;color:#999;text-align:center'>Page {pageNumber} of {totalPages}</div>",
};

using (var output = File.Create("invoice.pdf"))
{
    Render.ToPdf(html, output, options);
}

Console.WriteLine("Created invoice.pdf");

// HTML to PNG
using (var output = File.Create("invoice.png"))
{
    Render.ToImage(html, output, new RenderOptions { Dpi = 150f });
}

Console.WriteLine("Created invoice.png");

// CSS filter showcase — the same HTML rendered to PDF and PNG so the two can be
// compared. Every filter except plain opacity is rasterized into the PDF; the PDF
// and PNG should look the same.
var filtersHtml = @"
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 16px; }
        h2 { color: #333; margin: 8px 0; }
        .row { margin-bottom: 14px; }
        .box {
            display: inline-block; width: 88px; height: 88px; margin-right: 12px;
            background: linear-gradient(135deg, #ff5f6d, #1e5799 60%, #2c5364);
            border-radius: 10px; color: white; font-size: 12px; font-weight: bold;
            text-align: center; line-height: 88px; vertical-align: top;
        }
        .blur      { filter: blur(3px); }
        .shadow    { filter: drop-shadow(5px 5px 4px rgba(0,0,0,0.55)); }
        .gray      { filter: grayscale(1); }
        .sepia     { filter: sepia(1); }
        .bright    { filter: brightness(1.5); }
        .contrast  { filter: contrast(1.8); }
        .saturate  { filter: saturate(3); }
        .hue       { filter: hue-rotate(120deg); }
        .invert    { filter: invert(1); }
        .opacity   { filter: opacity(0.4); }
        .combo     { filter: grayscale(0.6) drop-shadow(3px 3px 3px #333); }
    </style>
</head>
<body>
    <h2>CSS Filters (PDF vs PNG)</h2>
    <div class='row'>
        <span class='box'>none</span>
        <span class='box blur'>blur</span>
        <span class='box shadow'>drop-shadow</span>
        <span class='box gray'>grayscale</span>
        <span class='box sepia'>sepia</span>
    </div>
    <div class='row'>
        <span class='box bright'>brightness</span>
        <span class='box contrast'>contrast</span>
        <span class='box saturate'>saturate</span>
        <span class='box hue'>hue-rotate</span>
        <span class='box invert'>invert</span>
    </div>
    <div class='row'>
        <span class='box opacity'>opacity</span>
        <span class='box combo'>combo</span>
    </div>
</body>
</html>";

var filterOptions = new RenderOptions
{
    PageSize = PageSize.Letter,
    MarginTop = 24f,
    MarginRight = 24f,
    MarginBottom = 24f,
    MarginLeft = 24f,
    Title = "CSS Filters",
};

using (var output = File.Create("filters.pdf"))
{
    Render.ToPdf(filtersHtml, output, filterOptions);
}

Console.WriteLine("Created filters.pdf");

using (var output = File.Create("filters.png"))
{
    Render.ToImage(filtersHtml, output, new RenderOptions { Dpi = 150f });
}

Console.WriteLine("Created filters.png");
