using System;
using System.IO;
using Rend;
using Rend.Core.Values;

// Simple HTML to PDF
using (var output = File.Create("hello.pdf"))
{
    Render.ToPdf("<h1>Hello, World!</h1><p>Generated by Rend.</p>", output);
}

Console.WriteLine("Created hello.pdf");

// With options
var html = @"
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; color: #333; }
        h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        .total { font-weight: bold; text-align: right; }
    </style>
</head>
<body>
    <h1>Invoice #1234</h1>
    <p>Date: 2024-01-15</p>
    <table>
        <tr><th>Item</th><th>Qty</th><th>Price</th></tr>
        <tr><td>Widget A</td><td>10</td><td>$50.00</td></tr>
        <tr><td>Widget B</td><td>5</td><td>$75.00</td></tr>
        <tr><td>Service Fee</td><td>1</td><td>$150.00</td></tr>
    </table>
    <p class='total'>Total: $1,025.00</p>
</body>
</html>";

var options = new RenderOptions
{
    PageSize = PageSize.Letter,
    MarginTop = 48f,
    MarginRight = 48f,
    MarginBottom = 48f,
    MarginLeft = 48f,
    Title = "Invoice #1234",
    Author = "Acme Corp",
    HeaderHtml = "<div style='font-size:9px;color:#999;text-align:right;padding-right:10px'>Acme Corp</div>",
    FooterHtml = "<div style='font-size:9px;color:#999;text-align:center'>Page {pageNumber} of {totalPages}</div>",
};

using (var output = File.Create("invoice.pdf"))
{
    Render.ToPdf(html, output, options);
}

Console.WriteLine("Created invoice.pdf");

// HTML to PNG
using (var output = File.Create("invoice.png"))
{
    Render.ToImage(html, output, new RenderOptions { Dpi = 150f });
}

Console.WriteLine("Created invoice.png");
